version: '3.4'

services:
  web:
    build: './'
    volumes:
      - './src:/var/www/html'
    ports:
      - '80:80'
    depends_on:
      - db

  db:
    #image: linuxserver/mariadb:alpine
    image: mysql:5.6
    restart: always
    volumes:
      - '../volumes/hhg/db:/var/lib/mysql'
    environment:
        MYSQL_ROOT_PASSWORD: changeme
        MYSQL_DATABASE: hhg
        MYSQL_USER: hhgdbuser
        MYSQL_PASSWORD: changeme

  tempserver:
    build: './'
    volumes:
      - '/tmp/exploit:/var/www/html'
    depends_on:
      - web
    ports:
      - "443:80"
